### ISSUE TITLE
Please provide all models

### ISSUE THREAD

**Issue by henryruhs** [instant-high/deoldify-onnx#2]
There are 3 models (Artistic, Stable and Video) ... could you upload each of them or provide the convert script?

**Comment by instant-high** [comment]
As said in setup.txt I did not convert the model myself.

You can find that one model, I think stable, and conversion script here (test_standalone_torch_fix_128.py):
https://github.com/KeepGoing2019HaHa/AI-application/tree/master/deoldify/ncnn

Please let me know if you have converted the other models, specially the video model ;-)

**Comment by henryruhs** [comment]
I see, thanks for letting me know. My guess: this ONNX is the old deoldify model.


For Stable and Video I get `RuntimeError: Error(s) in loading state_dict for DynamicUnetDeep` and a huge error messages with tons of ` size mismatch for layers`.

| Description                                 | Image                                                                                                    |
|---------------------------------------------|----------------------------------------------------------------------------------------------------------|
| ColorizeArtistic_gen.pth with 512x512 to ONNX | ![ColorizeArtistic_gen.pth with 512x512](https://github.com/instant-high/deoldify-onnx/assets/1835397/ea70571b-7dc2-41b1-9982-c8f9916905e9) |
| Comparison to the 256x256 unknown ONNX model    | ![Comparison to the 256 unknown ONNX model](https://github.com/instant-high/deoldify-onnx/assets/1835397/9073a341-a75c-40b5-a03d-0ba4e9295170) |

**Comment by henryruhs** [comment]
the convert script:

```python
import os

import torch
from deoldify.generators import gen_inference_deep
import torch.nn as nn
from pathlib import Path
from fastai.vision.data import normalize_funcs, imagenet_stats

norm, denorm = normalize_funcs(*imagenet_stats)

class ImageScaleInput(nn.Module):
	def __init__(self):
		super().__init__()
		self.norm = norm

	def forward(self, x):
		out = (x.div(255.0)).type(torch.float32)
		out, _ = self.norm((out, out), do_x=True)
		# out = out.unsqueeze(0)
		return out


class ImageScaleOutput(nn.Module):
	def __init__(self):
		super().__init__()
		self.denorm = denorm

	def forward(self, x):
		out = self.denorm(x, do_x=True)
		out = out.float().clamp(min=0, max=1)
		out = self.denorm(out, do_x=False)
		out = (out.mul(255.0)).type(torch.float32)
		return out


onnx_path = './deoldify/ColorizeArtistic_gen.onnx'
raw_model = gen_inference_deep(root_folder=Path('./deoldify'), weights_name='./deoldify/ColorizeArtistic_gen').model

dummy_input = torch.randn(1, 3, 512, 512)
final_pytorch_model = nn.Sequential(ImageScaleInput(), raw_model, ImageScaleOutput())
torch.onnx.export(
	final_pytorch_model,
	dummy_input,
	onnx_path,
	do_constant_folding=False,
	input_names=['input'],
	output_names=['output'],
	opset_version=10
)
```

**Comment by instant-high** [comment]
@henryruhs : I've changed your conversion script. Now you can convert all 3 models.
